### ISSUE TITLE
How I can get the classified fastq seqeuence?

### ISSUE THREAD

**Issue by biozhangzhou** [ChnMasterOG/KmerGO#1]
Hello Sir:
Thank you for that I can classified my fastq by using you software which are failed in jellyfish. There still some more needs. Could you please tell me the way to get the classified original sequences which corresponding to the specific kmer ?

**Comment by ChnMasterOG** [comment]
Thank you for using KmerGO.  And you can use **bowtie** which is a short read alignment tool to get the classified original sequences.
