### ISSUE TITLE
Question about R1 and R2 sequences

### ISSUE THREAD

**Issue by EunchongHuang** [ChnMasterOG/KmerGO#3]
Does KmerGo support pair-end sequencing data? If so, how does KmerGo merge R1 and R2 sequences? Does KmerGo merge R1 and R2 sequences through fastq-join? or are there any algorithms or pipelines for merging two sequences into one fastq?

**Comment by ChnMasterOG** [comment]
Pair-end sequencing data is supported by KmerGO(version >= 1.5.0b1), which can found in github release. In this version, R2.fq needs to be renamed to R1_1.fq so that it can be recognized by the program. However, KmerGO can only merge k-mer now.

**Comment by EunchongHuang** [comment]
> Pair-end sequencing data is supported by KmerGO(version >= 1.5.0b1), which can found in github release. In this version, R2.fq needs to be renamed to R1_1.fq so that it can be recognized by the program. However, KmerGO can only merge k-mer now.

**Comment by EunchongHuang** [comment]
Thank you for quick reply!  I'm trying to use KmerGO in 16s rRNA sequecing to find group specific kmer. According to your answer, surely, KmerGo does not support merging of two fastq into 'one merged fastq'. Instead KmerGo recognizes pair end sequencing file as independent file and extracts kmers independtly, and merge them into k-mer matrix. I'm curious to know, in your full knowledge, is the merging of two fastq files into one fastq process necessary before running KmerGO? Would the result be different given that all the parameters are same but differ in merging or not merging of fastq files?

**Comment by ChnMasterOG** [comment]
I don't understand the meaning of merging fastq. Do you mean that you put the fastq files end to end? In this way, i think the results are not different. The results depend on the k-mer counting of fastq files.

**Comment by EunchongHuang** [comment]
Merging of fastq for me meant pairwise fastq. Which mean one sample has two fastq file, one is forward fastq and another is reverse fastq.

**Comment by ChnMasterOG** [comment]
I suggest that you can use KmerGO v1.5.0b1 and input the pairwise fastq files directly.
