### ISSUE TITLE
'Parameters Error? Processes Break Down' Error

### ISSUE THREAD

**Issue by erin-thei** [ChnMasterOG/KmerGO#4]
Hello, 

Thank you for this tool. I have encountered an issue running it on assembled genomes. The first step finishes, and the second step (Kmer union) begins, but almost immediately returns the status as -9, with the error "Parameters error? Processes break down." 

The test files run successfully so I'm not sure what I am doing wrong.

Thanks in advance for your help!

**Comment by ChnMasterOG** [comment]
Wrong trait informations(traits do not correspond to file names) will cause this error. Please check it or show me the trait_information csv file.

**Comment by erin-thei** [comment]
Thanks for your response! Below is what the trait information csv file looks like: 


<img width="672" alt="Screen Shot 2022-11-28 at 3 49 14 PM" src="https://user-images.githubusercontent.com/108017953/204378664-dc99d734-6421-4b53-8c00-ef162b931c51.png">

**Comment by ChnMasterOG** [comment]
Thank you. It's a wrong format csv file for KmerGO1. You can remove all ".fasta" suffixes (refer to the format in README.md) and try again.

**Comment by erin-thei** [comment]
Awesome, got it to work. Thanks for your help!

**Comment by ChnMasterOG** [comment]
You are welcome.
